server:
  port: 8088
  contextPath: "/"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/GithubBotDB
    username: postgres
    password: postgres
    generate-ddl: false
springfox:
  documentation:
    swagger.v2.path: /rest/docs